AppBundle\Entity\UtoconsultMyArticleIndex:
    type: entity
    table: utoconsult_my_article_index
    indexes:
        utoconsult_my_article_index_id_utoconsult_my_article_id:
            columns:
                - id
    id:
        keyword:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: ''
            id: true
        field:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
            id: true
        position:
            type: bigint
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
    lifecycleCallbacks: {  }
