AppBundle\Entity\UtoconsultArticleCategory1:
    type: entity
    table: utoconsult_article_category1
    repositoryClass: AppBundle\Repository\Category1Repository
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        photo1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        keywords:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
