services:
    app_utoconsult.CacheService:
            class: AppBundle\Services\CacheService
            arguments: ["@service_container", "%cache.categories%", "%cache.homeArticles%", "%cache.articlesForCategory%"]
    app_utoconsult.SearchService:
            class: AppBundle\Services\SearchService
            arguments: ["@service_container", "@doctrine", "%fos_elastica.index_manager%"]
    app_utoconsult.CategoryService:
            class: AppBundle\Services\CategoryService
            arguments: ["@doctrine", "@session", "@app_utoconsult.CacheService"]       
    app_utoconsult.ArticleService:
            class: AppBundle\Services\ArticleService
            arguments: ["@doctrine", "@session", "@app_utoconsult.CacheService"]          
    app_utoconsult.controller.preExecuteListener:
        class: AppBundle\EventListener\ControllerListener
        tags:
          -  { name: kernel.event_listener, event: kernel.controller, method: onCoreController }   